### PR TITLE
fix: Build release linux

### PR DESCRIPTION
**Pull request by drminh2807**
Screenshot 2023-09-25 at 14 55 10

# Resolver
https://github.com/media-kit/media-kit#ubuntudebian

### CODE REVIEW

**Review by hoangdat — APPROVED** [review]

**Comment by drminh2807** [comment]
@tk-nguyen any idea to fix linux packager
I added fix for `build-linux-debug` step. As in description
but it still fail in `package-linux-debug` step
notice that I just change the `.github/workflows/tests.yaml` to easy observe the build result
will reverse it back after build success

**Comment by tk-nguyen** [comment]
What's the error?

**Comment by drminh2807** [comment]
@tk-nguyen https://github.com/linagora/twake-on-matrix/actions/runs/6296940697/job/17092903505?pr=674
Screenshot 2023-09-25 at 16 09 49

**Comment by tk-nguyen** [comment]
Try commenting the `build` step, and only let the `package` step run. If it works I'll rewrite how the build works.

**Comment by drminh2807** [comment]
> Try commenting the `build` step, and only let the `package` step run. If it works I'll rewrite how the build works.

It failed immediately

**Comment by tk-nguyen** [comment]
Hey, I've switched from AppImage to zip packaging to resolve this. See https://github.com/tk-nguyen/twake-on-matrix/commit/14bfaf85ff37b5ab8c0c28dcd434893ca7743ed1 for my changes.

**Comment by drminh2807** [comment]
> Hey, I've switched from AppImage to zip packaging to resolve this. See [tk-nguyen@14bfaf8](https://github.com/tk-nguyen/twake-on-matrix/commit/14bfaf85ff37b5ab8c0c28dcd434893ca7743ed1) for my changes.

@tk-nguyen  you are missing `mpv`
it must be ` libmpv-dev` and  `mpv`

**Comment by tk-nguyen** [comment]
> > Hey, I've switched from AppImage to zip packaging to resolve this. See [tk-nguyen@14bfaf8](https://github.com/tk-nguyen/twake-on-matrix/commit/14bfaf85ff37b5ab8c0c28dcd434893ca7743ed1) for my changes.
> 
> @tk-nguyen you are missing `mpv` it must be ` libmpv-dev` and `mpv`

No need, we just want the development libraries. `mpv` is the video player.

**Comment by drminh2807** [comment]
> > @tk-nguyen you are missing `mpv` it must be ` libmpv-dev` and `mpv`
> 
> No need, we just want the development libraries. `mpv` is the video player.

Are you sure, it is from library document
it can build, but not sure can run correctly

**Comment by tk-nguyen** [comment]
> Are you sure, it is from library document it can build, but not sure can run correctly

You can try with my built binaries: https://github.com/tk-nguyen/twake-on-matrix/releases/tag/v2.3.1

Note that to run on Linux you need to install some dependencies. On Ubuntu/Debian you should run `sudo apt install -y libjsoncpp-dev libmpv-dev`. This is because we're dynamically linking those libraries. 

It should work.

**Comment by drminh2807** [comment]
> > Are you sure, it is from library document it can build, but not sure can run correctly
> 
> You can try with my built binaries: https://github.com/tk-nguyen/twake-on-matrix/releases/tag/v2.3.1
> 
> Note that to run on Linux you need to install some dependencies. On Ubuntu/Debian you should run `sudo apt install -y libjsoncpp-dev libmpv-dev`. This is because we're dynamically linking those libraries.
> 
> It should work.

Your reason is not convincing enough
I have no linux OS so I can't test

**Comment by tk-nguyen** [comment]
> Your reason is not convincing enough I have no linux OS so I can't test

On Ubuntu/Debian, `libmpv-dev` and `mpv` has the same dependencies. `libmpv-dev` are for development headers, while `mpv` install runtime libraries. So for us, we need to install `libmpv-dev` and for users they need to install `mpv` (or `libmpv2`).

**Comment by drminh2807** [comment]
> > Your reason is not convincing enough I have no linux OS so I can't test
> 
> On Ubuntu/Debian, `libmpv-dev` and `mpv` has the same dependencies. `libmpv-dev` are for development headers, while `mpv` install runtime libraries. So for us, we need to install `libmpv-dev` and for users they need to install `mpv` (`libmpv2` on debian, `libmpv1` on ubuntu).

Oh I see
so User have to install libmpv then can run Twake app on linux
Can Twake app did it automatically ?

**Comment by tk-nguyen** [comment]
> > Oh I see
> > so User have to install libmpv then can run Twake app on linux
> > Can Twake app did it automatically ?

It needs to be packaged into deb or rpm format. Or we use the AppImage format, but as you can see it's quite broken right now.

(Sorry for editing your comment)

**Comment by drminh2807** [comment]
@tk-nguyen  have no experience with AppImage
Can you try to fix it 
eg: https://github.com/ivan-hc/MPV-appimage

**Comment by tk-nguyen** [comment]
> @tk-nguyen have no experience with AppImage Can you try to fix it eg: https://github.com/ivan-hc/MPV-appimage

I'm trying to fix it

**Pull request closed without merging**
