### PR TITLE
TW-1904: Improve style for backup dialog

### PR DESCRIPTION
**Pull request by nqhhdev**
### Ticket:
- #1904 

### DoD:

- [x] Update style for backup dialog on web
- [x] Update style for backup dialog on Mobile

### Resolved:

- Web:

https://github.com/linagora/twake-on-matrix/assets/99852347/d198713b-eb07-4eac-b21a-0cfcbf700d26

- Mobile

https://github.com/linagora/twake-on-matrix/assets/99852347/08f00eb4-22c8-4f28-ae76-2cd27284768b

- Responsive

https://github.com/linagora/twake-on-matrix/assets/99852347/e52814d3-4bd8-46ba-a93f-1dc3d560b287

### CODE REVIEW

**Comment by hieutbui** [comment]
Tested on:
- Windows browsers: Chrome, Edge, Firefox, Arc
- Android app
- IOS browsers: Safari, Chrome, Opera, Firefox, Arc

**Review by hieutbui — APPROVED** [review]

**Comment by Te-Z** [comment]
Hi @nqhhdev works fine and looks good. One last thing: for search text field you should remove the description and change icon color

image

**Comment by nqhhdev** [comment]
> Hi @nqhhdev works fine and looks good. One last thing: search text field should be also a skeleton or at least remove the description and change icon color
> 
> image

Updated, pls test it again

**Comment by Te-Z** [comment]
@nqhhdev could you update the demo video for mobile also please ?

image

**Comment by nqhhdev** [comment]
> @nqhhdev could you update the demo video for mobile also please ?
> 
> image

Done

**Review by Te-Z — APPROVED** [review]

**Pull request merged**
