### PR TITLE
TW-1615: Support auto jump to lastest message when user send an attachments 

### PR DESCRIPTION
**Pull request by nqhhdev**
### Ticket 

- #1615 

### Resolved

https://github.com/linagora/twake-on-matrix/assets/99852347/0ee94a53-9d4b-4840-8734-fb0d34e7af65

- Drag and drop 

https://github.com/linagora/twake-on-matrix/assets/99852347/d212beb9-43e4-4d29-b328-20641ad9c9a0

- Copy/paste

https://github.com/linagora/twake-on-matrix/assets/99852347/b1488da9-e72d-4ff3-b53d-4ccacd34652a

https://github.com/linagora/twake-on-matrix/assets/99852347/9565bcbf-ad68-430d-8914-f4bcd547be31

https://github.com/linagora/twake-on-matrix/assets/99852347/1741639b-4606-4c4d-9ffb-79be9834a660

### CODE REVIEW

**Comment by sherlockvn** [comment]
can you do the same with the case of `drag and drop` also the `copy/paste` images. thanks

**Review by Te-Z — APPROVED** [review]

**Review by sherlockvn — APPROVED** [review]

**Review by hieutbui — APPROVED** [review]

**Comment by Te-Z** [comment]
@nqhhdev still not working when copy pasting something 
[Capture vidéo du 29-05-2024 07:43:12.webm](https://github.com/linagora/twake-on-matrix/assets/31937920/a6f6a7ad-5ed4-4e7c-b912-36251f2b14cf)

**Comment by nqhhdev** [comment]
> @nqhhdev still not working when copy pasting something
> 
>  Capture.video.du.29-05-2024.07.43.12.webm


https://github.com/linagora/twake-on-matrix/assets/99852347/a7ca34e0-9fff-4499-b035-5a82b41d7db9

Just I tested it, works well on my branch

**Comment by Te-Z** [comment]
My bad, I did not pull before test it again. All good @nqhhdev !

**Comment by Te-Z** [comment]
Good job by the way :)

**Pull request merged**
