### PR TITLE
TW-596: change delivery status logic

### PR DESCRIPTION
**Pull request by imGok**
#596 

delvierdtest

### CODE REVIEW

**Comment by hoangdat** [comment]
@imGok pleaes use video instead of GIF, easy to understand and scroll to the position we want

**Comment by hoangdat** [comment]
https://github.com/linagora/twake-on-matrix/assets/6462404/c52d6dca-6dcd-41dd-880c-ae1a9fcffc66

something weird here. please check

**Comment by imGok** [comment]
> Screen.Recording.2023-09-15.at.15.04.11.mov 
> something weird here. please check

waiting for tom server to work again because I need multiple clients

**Comment by hoangdat** [comment]
> waiting for tom server to work again because I need multiple clients

can not understand, why it was `double blue` then come to `double gray` and then `double blue`. What is the problem?

**Comment by imGok** [comment]
> > waiting for tom server to work again because I need multiple clients
> 
> can not understand, why it was `double blue` then come to `double gray` and then `double blue`. What is the problem?

smth crashed not related to my PR so I pressed "continue" and it looks like this in the demo. But I'll check more deeply today

**Review by drminh2807 — APPROVED** [review]

**Comment by imGok** [comment]
I confirm it was a debug issue, tested it multiple times in build command. doesn't crash 

https://github.com/linagora/twake-on-matrix/assets/48354990/b775bf9b-3e18-4326-b583-1230f5edcf4b

**Review by hoangdat — APPROVED** [review]

**Pull request merged**
