### PR TITLE
TW-1439: Update UI for group information

### PR DESCRIPTION
**Pull request by nqhhdev**
### Ticket 

- #1439 

### Resolved

https://github.com/linagora/twake-on-matrix/assets/99852347/a8c86a79-768f-45a7-a7d3-5911dc0a8b51

https://github.com/linagora/twake-on-matrix/assets/99852347/6414572e-7eaa-46d6-a676-2f54a0a619b4

### CODE REVIEW

**Review by hieutbui — APPROVED** [review]

**Comment by hoangdat** [comment]
please update the correct circle avatar in group info

image

**Comment by nqhhdev** [comment]
> please update the correct circle avatar in group info
> 
> image

done

**Review by sherlockvn — APPROVED** [review]

**Comment by hoangdat** [comment]
image

**Comment by nqhhdev** [comment]
> image

Updated for padding in this case

https://github.com/linagora/twake-on-matrix/assets/99852347/c57e088c-ab50-4893-a52b-55025e124dac

**Review by hoangdat — APPROVED** [review]

**Pull request merged**
