### PR TITLE
TW-1271: Update UI for dialog invitation

### PR DESCRIPTION
**Pull request by nqhhdev**
### Ticket

- #1271 

### Resolved

https://github.com/linagora/twake-on-matrix/assets/99852347/0e3d03c0-1e56-411a-8752-5593a24ac460

### CODE REVIEW

**Comment by hoangdat** [comment]
Screenshot 2024-02-15 at 17 37 27

Padding of title is wrong

**Comment by sherlockvn** [comment]
Padding between Cancel and Add button is too big

**Comment by sherlockvn** [comment]
Screenshot 2024-02-16 at 09 49 47
Add a line the divide title and the list too

**Comment by nqhhdev** [comment]
Screenshot 2024-02-16 at 16 46 21

Updated

**Review by sherlockvn — APPROVED** [review]

**Review by hoangdat — APPROVED** [review]

**Pull request merged**
