### PR TITLE
fix: align web splash

### LINKED ISSUE #491: [web] Apply Splash screen for web
### Desc:

Image

### DoD:
- [ ] align the footer for splash screen

### PR DESCRIPTION
**Pull request by imGok**
image

demosplashh

- images are no more pixelated
- items are centered

This Closes #491

### CODE REVIEW

**Comment by nqhhdev** [comment]
IMO: 
Screenshot 2023-08-24 at 00 11 44

**Comment by drminh2807** [comment]
@nqhhdev  too high
@imGok  I think just add more space between bottom and LIN logo
I think 32dp or 64dp is okay

**Comment by nqhhdev** [comment]
> 

Yes,My image is example

**Comment by nqhhdev** [comment]
> @nqhhdev too high @imGok I think just add more space between bottom and LIN logo I think 32dp or 64dp is okay

Yes, My image is an example

**Review by drminh2807 — APPROVED** [review]

**Review by hoangdat — APPROVED** [review]

**Pull request merged**
