### PR TITLE
Use `xcbeautify` instead of `xcpretty`

### PR DESCRIPTION
**Pull request by tk-nguyen**
So errors does not get eaten up.

### CODE REVIEW

**Comment by drminh2807** [comment]
xcpretty already exist in `macos-latest`
https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md

**Comment by tk-nguyen** [comment]
> xcpretty already exist in `macos-latest` https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md

Yes, this is replacing `xcpretty` because `xcpretty` hides some errors, making it harder to debug.

**Comment by drminh2807** [comment]
but your PR just install it again, it not actually change use xcbeautify, (even though it works). you should find the correct way to enable it

**Comment by tk-nguyen** [comment]
> but your PR just install it again, it not actually change use xcbeautify, (even though it works). you should find the correct way to enable it

Don't see what you mean? It's using it in the script here: https://github.com/linagora/twake-on-matrix/actions/runs/7176075740/job/19540391658#step:9:360

**Review by drminh2807 — DISMISSED** [review]

**Review by hoangdat — APPROVED** [review]

**Pull request merged**
