### PR TITLE
hot-fix:TW-1812-remove x when searchbar is empty

### PR DESCRIPTION
**Pull request by KhaledNjim**
hot-fix for: https://github.com/linagora/twake-on-matrix/issues/1812

Removed x from search bar in contacts tab, chat creation and group chat creation

## Demo web

https://github.com/linagora/twake-on-matrix/assets/160496984/6c6ab9c0-4f20-42f0-a3b0-7d2e9ef5479e

## demo mobile 
[1812mobile.webm](https://github.com/linagora/twake-on-matrix/assets/160496984/aadf9518-6baa-43b5-a85c-9dd79cde42b1)

### CODE REVIEW

**Comment by nqhhdev** [comment]
Widget test build failed. Pls check it
- Be careful with changing test-related logic
- You can run `flutter analyze ` and `flutter test`

**Comment by hieutbui** [comment]
I think should re-write the test

**Comment by Te-Z** [comment]
Tested on 
- chrome
- android
- firefox
- gnome web
- opera

LGTM. 
Just need to adapt widget tests to your changes

**Review by Te-Z — APPROVED** [review]

**Comment by sherlockvn** [comment]
i tested in ios and it worked well.

https://github.com/linagora/twake-on-matrix/assets/43041967/621f0098-d3f9-4e23-8bb4-b30c90ccbbf7

**Comment by Te-Z** [comment]
> i tested in ios and it worked well.
> 
>  RPReplay_Final1720502804.MP4

@sherlockvn can you approve it then ?

**Review by sherlockvn — APPROVED** [review]

**Pull request merged**
