### PR TITLE
hot-fix: back to fluffy code for lines breaking

### PR DESCRIPTION
**Pull request by sherlockvn**

### CODE REVIEW

**Comment by hoangdat** [comment]
still have the problem with
```
hello https://github.com/linagora/twake-on-matrix/pull/1392



hello
```

**Comment by sherlockvn** [comment]
Please check it again, also the bullet points also after the deployment is success

**Comment by hoangdat** [comment]
still the same

**Comment by sherlockvn** [comment]
image
Which message do you get the error ?

**Comment by sherlockvn** [comment]
Failed case
"""
asdadsl


https://flutter.dev/global-gamers#guide

asddas
"""

**Comment by sherlockvn** [comment]
it's working now, the problem is the function `unmarkdownLink`

**Comment by sherlockvn** [comment]
I have tested some cases in this PR, right now, it's fine 
https://github.com/linagora/twake-on-matrix/pull/311

**Comment by imGok** [comment]
> it's working now, the problem is the function `unmarkdownLink`

we should delete it if we don't need it anymore.

I tested with "https://dantri.com.vn/xa-hoi/xu-ly-2-dia-diem-co-hien-tuong-nhieu-khoa-thong-minh-tai-ha-noi-20230625170424680.htm?_gl=1*18oxibc*_ga*MTkxNjE3OTU1MC4xNjY4NTk3NjE3" it's working fine

**Pull request merged**
