### PR TITLE
TW-1917: Create issue templates

### PR DESCRIPTION
**Pull request by hieutbui**
## Ticket
- #1917 

## Demo
https://github.com/hieutbui/test

https://github.com/linagora/twake-on-matrix/assets/80142234/6a64c90d-dd13-4e6b-aa22-a809ad02dd35

### CODE REVIEW

**Comment by sherlockvn** [comment]
image

IMO, you can create template in the settings, ask @hoangdat for this i think

**Comment by hieutbui** [comment]
> image
> IMO, you can create template in the settings, ask @hoangdat for this i think

I cannot access the setting and It will also do the same as I do via using setting

**Review by sherlockvn — APPROVED** [review]

**Review by Te-Z — APPROVED** [review]
LGTM could you ask @hoangdat to add this template in the repository ?

**Comment by hieutbui** [comment]
> LGTM could you ask @hoangdat to add this template in the repository ?

It will be added automatically after merge.

**Comment by hoangdat** [comment]
We should add `Environment` section to the bug report (maybe feature request too):
- Platform: iOS, Android, Web + version. Fx: Version 126.0.6478.127 (Official Build) (x86_64), Android P, ..... 
- App version: v2.5.9 
- ...

**Pull request merged**
