### PR TITLE
Improve/change the download icon in file

### PR DESCRIPTION
**Pull request by sherlockvn**
https://github.com/linagora/twake-on-matrix/assets/43041967/674ae724-f5ec-4104-9a0c-c0a8c62f220f

### CODE REVIEW

**Review by hoangdat — APPROVED** [review]

**Comment by hoangdat** [comment]
- [ ] can not download in web

**Comment by hieutbui** [comment]
From my side, download work well.

https://github.com/linagora/twake-on-matrix/assets/80142234/1eed8d6e-fd75-4266-bca4-6e389ad1f42d

**Comment by sherlockvn** [comment]
> * [ ]  can not download in web

image

**Comment by sherlockvn** [comment]
try with linagora server, it works well

**Review by hoangdat — APPROVED** [review]

**Review by hoangdat — APPROVED** [review]

**Pull request merged**
