### PR TITLE
TW-934: change online status of less than 1 minute to active now

### PR DESCRIPTION
**Pull request by imGok**
https://github.com/linagora/twake-on-matrix/assets/48354990/d5b92425-6326-4c2b-be2c-44d4e7058d6c

#934

### CODE REVIEW

**Comment by hoangdat** [comment]
please add demo video. Thanks.

**Comment by nqhhdev** [comment]
IMO: Should demo this case 
1. open 2 browsers with 2 accounts: Alice and Bob
2. Alice is offline and Bob is online 
3. Bob send some message to Alice
4. Alice is online

What happens when looking in chat Bob

**Review by drminh2807 — APPROVED** [review]

**Comment by imGok** [comment]
> IMO: Should demo this case
> 
> 1. open 2 browsers with 2 accounts: Alice and Bob
> 2. Alice is offline and Bob is online
> 3. Bob send some message to Alice
> 4. Alice is online
> 
> What happens when looking in chat Bob

this kind of demo are really hard since it's the server that automatically disconnects the user after x minutes

**Review by hoangdat — COMMENTED** [review]
please change also for this
```
      if (directChatPresence.presence == PresenceType.online) {
        return L10n.of(context)!.onlineStatus;
      }
```

to `Active now` too.

**Review by hoangdat — APPROVED** [review]

**Pull request merged**
