### PR TITLE
TW-1560 Support actions for chat messages

### PR DESCRIPTION
**Pull request by hieutbui**
## Ticket
- #1560 

## Resolved
- Android:

https://github.com/linagora/twake-on-matrix/assets/80142234/d166c00f-a81e-4846-9383-6ad77684da85

- Web:

https://github.com/linagora/twake-on-matrix/assets/80142234/b1e2f072-de13-4f75-8605-3daa1cf47a40

### CODE REVIEW

**Review by Te-Z — APPROVED** [review]

**Comment by nqhhdev** [comment]
IMO: In the case copy message, should show toast message, WDYT?

**Comment by sherlockvn** [comment]
Missing icon on unpin 
image

**Comment by hieutbui** [comment]
> IMO: In the case of copy message, should show toast message for copy message success, WDYT?

Agree, implemented

**Comment by hieutbui** [comment]
> Missing icon on unpin image

Fixed

**Review by sherlockvn — APPROVED** [review]

**Pull request closed without merging**
