### PR TITLE
TW-870: fix remove avatar

### PR DESCRIPTION
**Pull request by imGok**
#870 
sdk : https://github.com/linagora/matrix-dart-sdk/pull/32

https://github.com/linagora/twake-on-matrix/assets/48354990/a4fc227f-0fcb-4122-9024-d0d38dfd1d4b

### CODE REVIEW

**Comment by nqhhdev** [comment]
Pls check it again. Profile information widget is center
Screenshot 2023-11-03 at 09 08 39

**Comment by imGok** [comment]
@nqhhdev out of the scope, we should fix on another pr

**Comment by hoangdat** [comment]
> @nqhhdev out of the scope, we should fix on another pr 

But it maybe make a side effect, if we can not find the root cause, we can not merge this PR

**Comment by imGok** [comment]
> Pls check it again. Profile information widget is center Screenshot 2023-11-03 at 09 08 39

center bug is on main too i'll fix it on this PR as you told me

**Review by nqhhdev — APPROVED** [review]

**Review by sherlockvn — APPROVED** [review]

**Comment by imGok** [comment]
please don't merge if all approved I need to change pubspec.lock

**Comment by hoangdat** [comment]
hi @imGok please update the pubspec file. Thanks

**Review by drminh2807 — APPROVED** [review]

**Review by nqhhdev — APPROVED** [review]

**Review by hoangdat — APPROVED** [review]

**Pull request merged**
