### PR TITLE
config default homeserver when debug

### PR DESCRIPTION
**Pull request by sherlockvn**

### CODE REVIEW

**Comment by drminh2807** [comment]
@sherlockvn  what do you think if we can use `config.json`

**Comment by sherlockvn** [comment]
> config.json

i only see the config.sample.json file.

**Comment by drminh2807** [comment]
> > config.json
> 
> i only see the config.sample.json file.

you only see config.sample.json file is correct
 it is template file
 common behavior when setup a project env:
 - Duplicate config.sample.json
 - Change name to config.json
 - content in config.json will override default config
 - config.json should be in .gitignore

**Comment by sherlockvn** [comment]
> > > config.json
> > 
> > 
> > i only see the config.sample.json file.
> 
> you only see config.sample.json file is correct it is template file common behavior when setup a project env:
> 
> * Duplicate config.sample.json
> * Change name to config.json
> * content in config.json will override default config
> * config.json should be in .gitignore

Thanks, I try it when have time.

**Comment by sherlockvn** [comment]
Closed because i handled it in another ticket

**Pull request closed without merging**
