### PR TITLE
TW-777: refactor all messages content

### PR DESCRIPTION
**Pull request by imGok**
#777

Mobile 

image

Web 

image

No delete functionality 

image

### CODE REVIEW

**Comment by hoangdat** [comment]
for the `redact` or `encrypted`:
- maxLines: 2
- should have maxWidth

**Review by drminh2807 — APPROVED** [review]

**Comment by hoangdat** [comment]
image

Why the quote and the original bubble not the same.

**Comment by hoangdat** [comment]
- `This message has been redacted`

**Comment by imGok** [comment]
@hoangdat done

**Comment by hoangdat** [comment]
> @hoangdat done

please demo

**Comment by imGok** [comment]
@hoangdat demo in description

**Review by drminh2807 — APPROVED** [review]

**Review by hoangdat — APPROVED** [review]

**Pull request merged**
