### PR TITLE
TW-1830 changed text when user has no contacts

### PR DESCRIPTION
**Pull request by KhaledNjim**
## Issue
#1830 

## Demo android
https://github.com/linagora/twake-on-matrix/assets/160496984/af271683-1c91-4289-9fb1-2daa8b131f12

## Demo web

https://github.com/linagora/twake-on-matrix/assets/160496984/36ea547d-e7c3-406b-83b2-fe5135757b8c

### CODE REVIEW

**Review by Te-Z — APPROVED** [review]

**Comment by Te-Z** [comment]
Please run `dart format --set-exit-if-changed lib/ test/` and push again

**Review by hieutbui — APPROVED** [review]

**Comment by sherlockvn** [comment]
I think you should make the text at the center, to have better UI, UX. wdyt @Te-Z ?

Screenshot 2024-06-13 at 14 51 55

**Comment by Te-Z** [comment]
> I think you should make the text at the center, to have better UI, UX. wdyt @Te-Z ?
> 
> Screenshot 2024-06-13 at 14 51 55

I agree. Could you please center it @KhaledNjim  ?

**Comment by KhaledNjim** [comment]
> > I think you should make the text at the center, to have better UI, UX. wdyt @Te-Z ?
> > Screenshot 2024-06-13 at 14 51 55
> 
> I agree. Could you please center it @KhaledNjim ?
done

**Review by Te-Z — APPROVED** [review]

**Comment by Te-Z** [comment]
LGTM, please squash and rebase

**Comment by KhaledNjim** [comment]
> LGTM, please squash and rebase @KhaledNjim

done

**Pull request merged**
